### ISSUE TITLE
Limit the number of concurrent requests to song-search so it does not crash song-search

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/donor-submission-aggregator#232]
A change is needed to the donor-submission-aggregator, needs to limit the number of concurrent requests to song-search. RDPC song-search is crashing as a result of being overloaded. This will be smaller chunks and queued up one after the other. 

Example of when this happens: data on the submitter pages are triggered in the UI to resync the program, but this crashes.

**Comment by joneubank** [comment]
After investigation of the sync workflow, can confirm that this service is running all requests in series. The concurrency issue observed on song-search is not being generated by the Donor Aggregator, so there is no fix needed here.

A couple additional points that need attention though:
- The Sync event handler takes a long time to complete, this causes kafka to kick it out as a consumer since it does not send a signal within the default session timeout.
  - changing the value of `KAFKA_PROGRAM_QUEUE_CONSUMER_SESSION_TIMEOUT` to something very large like 15 minutes (900000) can get the kakfa events handled, but this isn't a stable long term solution. I will open another ticket to solve this issue without needing a massive session timeout
- Changing the page size sent to rdpc gateway with the config property `STREAM_CHUNK_SIZE` can reduce errors from the rdpc by reducing the number of concurrent requests it generates.
  - Setting this to `10` results in most sync attempts succeeding.

Therefore, changing these configs is able to get the resync working, but investigation is required on the donor aggregator Kafka interaction, and on the rdpc-gateway request generation to song-search.

**Comment by joneubank** [comment]
New issue discovered around the session timeout problem: https://github.com/icgc-argo/donor-submission-aggregator/issues/233
